account_id = "8f0c2f2271ff857947d9a5b2c38595a0"
zone_id = "cb31764917040dd0b9a7b79e1ec099df"

main = "../build/demo-mapping/prod.js"
name = "kimlikdao-demo-mapping"
route = { pattern = "demo-mapping.kimlikdao.org", custom_domain = true }

workers_dev = false
no_bundle = true
minify = false
send_metrics = false
node_compat = false
logpush = false

rules = [{ type = "Text", globs = [], fallthrough = false }]

[[kv_namespaces]]
binding = "KV"
id = "69151547872a4169a58214617ae98842"
