account_id = "8f0c2f2271ff857947d9a5b2c38595a0"

main = "../build/discord/prod.js"
name = "kimlikdao-discord"
route = { pattern = "discord.kimlikdao.org", custom_domain = true }

workers_dev = false
no_bundle = true
minify = false
send_metrics = false
node_compat = false
logpush = false

rules = [{ type = "Text", globs = [], fallthrough = false }]

[[kv_namespaces]]
binding = "KV"
id = "84ae9125ab654c4ca5511acbe63e269f"
preview_id = "84ae9125ab654c4ca5511acbe63e269f"
