name: All tests

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  build-blog:
    name: Build KimlikDAO blog
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install build tools
        run: |
          bun i
          brew install pngcrush brotli zopfli woff2 webp
          pip install fonttools

      - name: Build blog index
        run: |
          make blog/dizin.sayfa

      - name: Build prod worker
        run: |
          make build/blog/sunucu/prod.js

  build-join:
    name: Build KimlikDAO join
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install build tools
        run: |
          bun i
          brew install pngcrush brotli zopfli woff2 webp
          pip install fonttools

      - name: Build join page
        run: |
          make join.sayfa

      - name: Build prod worker
        run: |
          make build/join/prod.js

  build-discord:
    name: Build KimlikDAO discord worker
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install build tools
        run: |
          bun i

      - name: Build discord worker
        run: |
          make build/discord/prod.js
